# Generated by Django 3.2.16 on 2023-03-06 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_rename_data_alunos_data_nascimento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alunos',
            new_name='Aluno',
        ),
    ]
