# Generated by Django 3.2.16 on 2023-03-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_rename_alunos_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
